branches:
  - "+([0-9])?(.{+([0-9]),x}).x"
  - main
  - next
  - next-major
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/changelog"
  - - "@google/semantic-release-replace-plugin"
    - replacements:
        - files:
            - runcc/Cargo.toml
          from: 'version = ".*" # replace version'
          to: 'version = "${nextRelease.version}" # replace version'
          results:
            - file: runcc/Cargo.toml
              hasChanged: true
              numMatches: 1
              numReplacements: 1
          countMatches: true
  - - "@semantic-release/exec"
    - publishCmd: cd runcc && cargo publish
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - runcc/Cargo.toml
  - "@semantic-release/github"
